### ISSUE TITLE
dumping is formating custom type wrong

### ISSUE THREAD

**Issue by rubendmatos1985** [nodeca/js-yaml#576] opened 2020-08-29 16:29 UTC
```
const yaml = require("js-yaml")

class Test {
  constructor(id) {
    this.id = id
  }
  id

  get Id() {
    return this.id
  }
  async fetchData() {
    console.log("get async data")
  }
}



var customtagYamlType = new yaml.Type("!mapInfo", {
  kind: "scalar",
  resolve: () => true,
  construct: (id) => new Test(id),
  instanceOf: Test,
  represent: (customTag) => customTag.id,
})

const obj = {
  name: 'some',
  data:{
    content:[
      {
        value: new Test("1")
      }
    ]
  }
}


const schema = yaml.Schema.create([customtagYamlType])

const result = yaml.dump(obj, { schema })
console.log(result)

/* the output is 
data:
  content:
  - value: !<!mapInfo> '1'

-----------------------------------------
i am expecting like in the documentation
data:
  content:
  - value: !mapInfo  '1'



node version v12.14.1
  

*/

```

**Comment by rlidwka** [comment] 2020-09-15 17:16
Those string representations are equivalent:

```js
console.log(yaml.load(`
a: !<!mapInfo> '1'
b: !mapInfo '1'
`, { schema }))

// prints { a: Test { id: '1' }, b: Test { id: '1' } }
```

`!<!mapInfo>` is a global version of the application-local tag `!mapInfo`, both variants are acceptable I believe.

Does it cause any issues (e.g. interoperability with other parsers)?

**Comment by rubendmatos1985** [comment] 2020-09-18 10:55
Yes they are equivalent but the same library throw an error when convert from ``` !mapInfo ```  to ``` !<!mapInfo> ```  i have to use ``` string.replace('!<!mapInfo>', '!mapInfo' ) ```  after dumping

**Comment by danmactough** [comment] 2020-10-04 02:37
+1 I am also working on a library where I want to be able to load yaml with custom tags, process/transform the data, and then dump the transformed data as yaml while preserving the original -- I want to be able to perform a diff and don't want every custom tag rewritten.

If we had an option available when creating a Type (for example, a boolean flag -- `dumpTagsWithGlobalWrapper`), it seems like [here](https://github.com/nodeca/js-yaml/blob/2d1fbed8f3a76ff93cccb9a8a418b4c4a482d3d9/lib/js-yaml/dumper.js#L665), we could propagate that option to the `state` with something like `state.dumpTagsWithGlobalWrapper = !!type.dumpTagsWithGlobalWrapper`. Then where we currently add that wrapper [here](https://github.com/nodeca/js-yaml/blob/2d1fbed8f3a76ff93cccb9a8a418b4c4a482d3d9/lib/js-yaml/dumper.js#L757-L759), we could conditionally add the wrapper or not.

Would you accept a PR for this?

**Comment by rlidwka** [comment] 2020-12-25 19:09
Fixed in https://github.com/nodeca/js-yaml/commit/a0d0caa5aa0f5354fefa9c637cfb7c4c17ef7d02 (currently in `dev` branch).

Now tag behavior aligns with `pyyaml`, where custom tags are dumped as `!tag`, and there is no way to dump those as `!<!tag>`. Please tell me if there's any use-case for the old behavior.

Duplicate of:
https://github.com/nodeca/js-yaml/issues/364
https://github.com/nodeca/js-yaml/pull/187

**Closed by rlidwka** 2020-12-25 19:09 UTC
