### ISSUE TITLE
Ability to switch to flow style for simple objects

### ISSUE THREAD

**Issue by pokey** [nodeca/js-yaml#635] opened 2021-07-27 23:45 UTC
I'd like to be able to automatically switch to flow style for objects / arrays where each value is not an object or an array.  Eg you'd get

```yaml
foo: {bar: "baz"}
```

but

```yaml
foo:
  bar:
    - baz
```

Ideally you'd be able to say this only happens if object / arrays with a max number of entries, but that's definitely extra credit

**Comment by rlidwka** [comment] 2021-07-28 16:45
I've come up with this hack recently that'd allow you to serialize objects however you like: https://github.com/nodeca/js-yaml/issues/586#issuecomment-814310104, https://github.com/nodeca/js-yaml/issues/613#issuecomment-814319894

Would it be fine for your case?

*closing as a duplicate of #586, #613, we just can't add every possible formatting option anyone can think of*

**Closed by rlidwka** 2021-07-28 16:45 UTC

**Comment by pokey** [comment] 2021-07-28 17:49
yeah I think that should do the trick thanks.  Fwiw my proposal is the default behaviour in pyyaml. But given that this library was inspired by pyyaml, I'm guessing you moved away from that default for a reason 🙂

thanks for the quick response!

**Comment by pokey** [comment] 2021-08-05 13:57
Fwiw, here's what I ended up with.  It's technically typescript, but I haven't gotten around to adding any real types

```ts
// @ts-nocheck
// Based on https://github.com/nodeca/js-yaml/issues/586#issuecomment-814310104
// This file ensures that simple objects and arrays (ie without array or object
// children) will be serialized inline, and also ensures that "fullTargets" will be inlined as well
// TODO: Add types
import * as yaml from "js-yaml";

function customDump(data: unknown, opts) {
  if (!(this instanceof customDump)) {
    return new customDump(data, opts);
  }
  this.data = data;
  this.opts = opts;
}

customDump.prototype.represent = function () {
  let result = yaml.dump(
    this.data,
    Object.assign({ replacer, schema }, this.opts)
  );
  result = result.trim();
  if (result.includes("\n")) {
    result = "\n" + result;
  }
  return result;
};

const customDumpType = new yaml.Type("!format", {
  kind: "scalar",
  resolve: () => false,
  instanceOf: customDump,
  represent: (d) => d.represent(),
});

let schema = yaml.DEFAULT_SCHEMA.extend({ implicit: [customDumpType] });

const isObject = (value: unknown) => typeof value === "object" && value != null;

function hasSimpleChildren(value: unknown) {
  if (isObject(value)) {
    return Object.values(value).every(
      (value) => !isObject(value) && !Array.isArray(value)
    );
  }
  if (Array.isArray(value)) {
    return value.every((value) => !isObject(value) && !Array.isArray(value));
  }
}

function replacer(key: string, value: unknown) {
  if (key === "") {
    return value;
  } // top-level, don't change this

  if (hasSimpleChildren(value)) {
    return customDump(value, { flowLevel: 0 });
  }

  return value; // default
}

const serialize = (obj: unknown) =>
  customDump(obj, { noRefs: true, quotingType: '"' }).represent().trim();

export default serialize;
```
