### ISSUE TITLE
Emoji 🦐 escaped

### ISSUE THREAD

**Issue by cristianvasquez** [nodeca/js-yaml#600] opened 2020-12-21 13:21 UTC
Hello, 

Thanks for js-yaml!.

My report: 

```javascript
const jsYaml = require('js-yaml');
console.log(jsYaml.safeDump({'key': "🦐"}))
// outputs:
// key: "\U0001F990"
```

I expect to have the 🦐 back.

**Comment by rlidwka** [comment] 2020-12-21 13:57
This is going to be fixed in 4.0.0 (you can look it up now in `dev` branch in this repository).

closing as duplicate of https://github.com/nodeca/js-yaml/issues/587

**Closed by rlidwka** 2020-12-21 13:57 UTC

**Comment by cristianvasquez** [comment] 2020-12-21 13:58
Thanks @rlidwka !

**Comment by cristianvasquez** [comment] 2021-02-22 12:12
Hello @rlidwka what happened with the dev branch of this repo?

**Comment by puzrin** [comment] 2021-02-22 12:14
It's merged to master. Your request should be in released v4.

**Comment by cristianvasquez** [comment] 2021-02-22 12:21
Thanks! :)
