### ISSUE TITLE
Support ignoring tags, without needing a schema

### ISSUE THREAD

**Issue by TMiguelT** [nodeca/js-yaml#566] opened 2020-07-16 10:45 UTC
I have a complex data model that uses tags, but at the point where js-yaml touches it, I really don't care about the tags. I would like to be able to load the data without manually specifying each and every custom tag I've used as a schema.

Might it be possible to have a `PERMISSIVE_SCHEMA` that simply takes mapping types and converts them to JS objects, and takes sequence types and converts them to arrays? I suspect this is a somewhat common use-case.

In general, this would be a quick-and-dirty solution to the error:
```
YAMLException: unknown tag !<!MyTag> at line 8, column 1:
```

**Comment by puzrin** [comment] 2020-11-28 15:21
Dupe of #385

**Closed by puzrin** 2020-11-28 15:21 UTC

**Comment by rlidwka** [comment] 2020-12-25 19:27
You can now construct custom permissive schema, feature added in https://github.com/nodeca/js-yaml/commit/73ef02cfcb63d9f1c5932dadc1fc35f05a25fdbc (currently in `dev` branch, not released yet).

(example: https://github.com/nodeca/js-yaml/blob/a0d0caa5aa0f5354fefa9c637cfb7c4c17ef7d02/examples/handle_unknown_types.js)
