### ISSUE TITLE
How to specify flow level of a specific element?

### ISSUE THREAD

**Issue by roipoussiere** [nodeca/js-yaml#613] opened 2021-03-22 11:07 UTC
I have this data:

```json
{
  "dict": [
    {
      "foo": [
        "bar"
      ]
    }
  ],
  "array": [
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
  ]
}
```

And I would like dump it like this:

```yaml
dict:
- foo:
  - bar
arrays:
- [1, 2, 3, 4, 5]
- [6, 7, 8, 9, 10]
```

Ie. indent all elements except `array` items.

I know I can use `flowLevel` to specify level of nesting, but how to apply it only for one item in data?

**Comment by rlidwka** [comment] 2021-04-06 17:04
Not possible at the moment (unless you want to employ excessive amounts of hacking).

We can't add this option, because people are asking for dozens (if not hundreds) of these, and adding every one of them would bloat dumper API too much.

Any ideas for custom formatting perhaps?

**Comment by rlidwka** [comment] 2021-04-06 17:54
closing as duplicate of https://github.com/nodeca/js-yaml/issues/586

**Closed by rlidwka** 2021-04-06 17:54 UTC

**Comment by rlidwka** [comment] 2021-04-06 17:55
just like in the ticket above, here's a hacky solution which you can use at your own risk:

```js
const yaml = require('js-yaml');

function CustomDump(data, opts) {
  if (!(this instanceof CustomDump)) return new CustomDump(data, opts);
  this.data = data;
  this.opts = opts;
}

CustomDump.prototype.represent = function () {
  let result = yaml.dump(this.data, Object.assign({ replacer, schema, noArrayIndent: true }, this.opts));
  result = result.trim();
  if (result.includes('\n')) result = '\n' + result;
  return result;
}


let CustomDumpType = new yaml.Type('!format', {
  kind: 'scalar',
  resolve: () => false,
  instanceOf: CustomDump,
  represent: d => d.represent()
});


let schema = yaml.DEFAULT_SCHEMA.extend({ implicit: [ CustomDumpType ] });

function replacer(key, value) {
  if (key === '') return value; // top-level, don't change this
  if (Array.isArray(value) && value.length > 4) return CustomDump(value, { flowLevel: 0 });
  return value; // default
}

console.log(CustomDump(
{
  "dict": [
    {
      "foo": [
        "bar"
      ]
    }
  ],
  "array": [
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
  ]
}
).represent().trim());

/* Returns:

dict:
- foo:
  - bar
array:
- [1, 2, 3, 4, 5]
- [6, 7, 8, 9, 10]
*/
```
